### ISSUE TITLE
Fails to start on Ubuntu 24.04: ModuleNotFoundError: No module named 'encodings'

### ISSUE THREAD

**Issue by magpie514** [ivan-hc/Bottles-appimage#10]
After updating to Ubuntu 24.04 the appImage has stopped working. 
It fails with the following output. Let me know if you need any additional information!
```
Python path configuration:
  PYTHONHOME = '/tmp/.mount_BottleoiBdla/usr/'
  PYTHONPATH = '/tmp/.mount_BottleoiBdla/usr/lib/python3.11/site-packages/:/tmp/.mount_BottleoiBdla/usr/lib/python3.11/lib-dynload/:'
  program name = '/usr/bin/python3'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/tmp/.mount_BottleoiBdla/usr/lib/python3.12'
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/tmp/.mount_BottleoiBdla/usr/'
  sys.base_exec_prefix = '/tmp/.mount_BottleoiBdla/usr/'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/tmp/.mount_BottleoiBdla/usr/'
  sys.exec_prefix = '/tmp/.mount_BottleoiBdla/usr/'
  sys.path = [
    '/tmp/.mount_BottleoiBdla/usr/lib/python3.11/site-packages',
    '/tmp/.mount_BottleoiBdla/usr/lib/python3.11/lib-dynload',
    '/home/magpie/Downloads',
    '/tmp/.mount_BottleoiBdla/usr/lib/python312.zip',
    '/tmp/.mount_BottleoiBdla/usr/lib/python3.12',
    '/tmp/.mount_BottleoiBdla/usr/lib/python3.12/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000778579806940 (most recent call first):
  <no Python frame>
```

## Python version:
```
$python3 --version
Python 3.12.3
```

**Comment by ivan-hc** [comment]
Hi, sadly I can't do much right now, because the AUR package in use has not been updated by its maintainer, its stuck at March, 2024 https://aur.archlinux.org/packages/bottles and in the meantime, Arch Linux have updated python 3.11 to 3.12.

I can still build this on a normal Arch Linux installation, but not for this kind of AppImage package.

This is why I also have two pending issues like this: https://github.com/ivan-hc/Bottles-appimage/issues/9 and https://github.com/ivan-hc/Bottles-appimage/issues/8

All we can do is to convince tha maintainer of the AUR package, because upstream Bottles developers only care about Flatpak without exiting fromt their "bubble"/"compfort zone".

Sorry.

**Comment by magpie514** [comment]
That's unfortunate. Is it okay if I leave this open to keep track of it when it's resolved upstream?

**Comment by ivan-hc** [comment]
I'll keep you all updated in case I find a better solution.

However the main issue is that Bottles upstream developers (not Mirko, the creator, but its collaborators) are against packaging out of Flatpak... and I'm pretty sure that if someone stopped updating the PKGBUILD is because they have noticed I broke their rule.

**Comment by ivan-hc** [comment]
Hi again, now I can build the Appimage using an Arch Linux snapshot of March https://github.com/ivan-hc/Bottles-appimage/commit/2750749625667f50c8ecd8a2df6b9fec646811fc

I've already said in the other [issue](https://github.com/ivan-hc/Bottles-appimage/issues/8#issuecomment-2198411223) what is the problem, from the AppRun to the libraries of the host needed by the AppImage.

About your issue, my AppImage is built to see also system libraries, and your error is refering to missing module named "encodings", that should be contained in `python3-chardet`. If it is not installed, you should install it and retry.

I know that such libraries should be bundled into the AppImage, and they are, I only have to guess and fix the AppRun with the needed variables... but I don't know what is the correct way to run Bottles as an Appimage if not so.

Let me know if this works for you, I'll update the README in the meantime to let you all know what are packages used from both Debian and Arch.

**Comment by ivan-hc** [comment]
I think once we fix https://github.com/ivan-hc/Bottles-appimage/issues/8 we solve this and any compatibility issue.

**Comment by magpie514** [comment]
Hmm, I do have chardet installed, actually.
![image](https://github.com/ivan-hc/Bottles-appimage/assets/323651/9d6e7312-ab13-467c-b087-7b1d029f194e)
But the LD_LIBRARY_PATH approach might be the way to go. *Seems* it's trying to use the system `/usr/bin/python3` binary and looking for the packaged libraries instead of the system's with a wrong version, and that's what's making it explode. 
I completely forgot appRun scripts tend to use that env variable, so the issue makes a lot more sense now, if that's the case.

I hope you can figure it out, seems you are getting close.

**Comment by ivan-hc** [comment]
I've completelly removed LD_LIBRARY_PATH from the AppRun in the last commit, can you extract the AppImage with the option `--appimage-extract`, remove/comment the line and try to start Bottles from the AppRun?

**Comment by magpie514** [comment]
Will do, give me a minute, I'll edit this message with the results.

**Comment by ivan-hc** [comment]
can you try to rebuild the AppImage by following the instructions of the 8 videos I shared at https://github.com/ivan-hc/Bottles-appimage/issues/8#issuecomment-2198639489 ?

be sure you have `imagemagick` and `glib-compile-schemas` installed on your system

**Comment by ivan-hc** [comment]
I'll come back from about 30 minutes or less

**Comment by magpie514** [comment]
Before that, I noticed a thing:
```sh
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
export UNION_PRELOAD="${HERE}"
export LD_PRELOAD="${HERE}"/libunionpreload.so:"${HERE}"/usr/lib/x86_64-linux-gnu/libcurl.so
export PATH="${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${HERE}"/bin/:"${HERE}"/sbin/:"${PATH}"
export PYTHONPATH="${HERE}"/usr/lib/python3.11/site-packages/:"${HERE}"/usr/lib/python3.11/lib-dynload/:"${PYTHONPATH}"
export PYTHONHOME="${HERE}"/usr/
export XDG_DATA_DIRS="${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
export PERLLIB="${HERE}"/usr/share/perl5/:"${HERE}"/usr/lib/perl5/:"${PERLLIB}"
export GSETTINGS_SCHEMA_DIR="${HERE}"/usr/share/glib-2.0/schemas/:"${GSETTINGS_SCHEMA_DIR}"
printf "\nHERE: %s, LD_LIBRARY_PATH: %s\n" "$HERE" "$LD_LIBRARY_PATH"
case "$1" in
	'') $HERE/usr/bin/${EXEC};;
	*) $HERE/usr/bin/bottles-cli "$@";;
esac
```
I moved the grep/sed calls to before you alter PATH, it's trying to use my system's sed and grep because it cannot find them in the new environment. Now the error is about it trying to use my system's python instead:
![image](https://github.com/ivan-hc/Bottles-appimage/assets/323651/2155345c-33b4-4bfe-8943-7d062cf9188f)

**Comment by magpie514** [comment]
Rebuilding gives the same issues. No LD_LIBRARY_PATH might be a bad thing after all.
However, even setting it in a way where local system libraries are last it still tries to use the system's python3, which in this case is 3.12. 
Other things I tried:
* Adding symlinks `python3` and `python` pointing to $HERE/usr/bin/python3.11, still tries to use system's `/usr/bin/python3`
* Changing PYTHONHOME to `export PYTHONHOME="${HERE}"/usr/:"$HERE"/usr/bin` : Same problem
HOWEVER
* Changing `#!/usr/bin/python3` to `#!/usr/bin/env python3` in `bottles-cli` and `bottles` (⚠️never use hardcoded paths for those!) has changed something:
![image](https://github.com/ivan-hc/Bottles-appimage/assets/323651/e67770ce-ce11-42d5-a238-74ff6126ee3a)

So I started over and ONLY edited `bottles` and `bottles-cli` and replaced the shebang (#!) to `#!/usr/bin/env python3.11` with *no other changes* and...
![image](https://github.com/ivan-hc/Bottles-appimage/assets/323651/47a6a0b2-d074-40f5-b336-d18a6defdfa5)
Try building on your side with only changing those headers, please.

**Comment by ivan-hc** [comment]
So I should include LD_LIBRARY_PATH?

**Comment by magpie514** [comment]
Yeah, seems the only change that needs to be done is changing the shebangs in those python scripts so it doesn't try to use the user's system python.

**Comment by magpie514** [comment]
Seems functional so far, wineserver is running and creating the instances fine. 
Errors pop up here and there such as
```
wine: could not open working directory L"unix\\home\\magpie\\.local\\share\\bottles\\bottles\\test\\", starting in the Windows directory.
```
Which make me wonder where it's getting an "unix" path, but seems harmless.
```
ERROR: ld.so: object '/home/magpie/Downloads/squashfs-root/libunionpreload.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```
Those mystify me, but seem to be completely harmless?
But now I can install a bottle and reach the registry editor, meaning everything is working at a basic level.

Seems you can close this issue once you publish updated packages, unless you prefer me to close it now.

**Comment by ivan-hc** [comment]
I can confirm that his works for me, the only thing I would to test is running/installing programs

**Comment by ivan-hc** [comment]
![Istantanea_2024-07-01_00-59-43 png](https://github.com/ivan-hc/Bottles-appimage/assets/88724353/1c012779-3d8d-4199-bb88-23df4f9dad5f)

I think is better to keep talking at https://github.com/ivan-hc/Bottles-appimage/issues/8

**Comment by magpie514** [comment]
Just to confirm, the latest appImage release does fix this issue. Now let's see if we can figure out the path issues.
