### ISSUE TITLE
your this appimag have sames bug 

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/Bottles-appimage#11]
![image](https://github.com/user-attachments/assets/4bde9240-aae2-4e9b-a20d-afa5ef05278e)

relative post
https://github.com/ivan-hc/Boxes-appimage/issues/3

**Comment by newyorkthink** [comment]
![image](https://github.com/user-attachments/assets/a2208224-7ee9-4f31-affb-99ab2e818fae)

is auto close

**Comment by newyorkthink** [comment]
and icons is missing
![image](https://github.com/user-attachments/assets/07a5f937-b438-4651-b4c7-5dbd414574e9)

**Comment by newyorkthink** [comment]
if you can,
nstalling dependency: Wine mono …
Installing dependency: Wine gecko …

this is to long
this wine pacekage is inclode this
https://github.com/mmtrt/WINE_AppImage
![image](https://github.com/user-attachments/assets/61e5145d-17a1-4c4d-97bd-6fab6650ab8b)

is link to /tmp

**Comment by newyorkthink** [comment]
and suggestion some thing:

please max for the /tmp 

conty.sh is need more /tmp size
![image](https://github.com/user-attachments/assets/7cedac9c-8f4e-4a54-aab8-ff408d4ad21a)

**Comment by ivan-hc** [comment]
By following your instructions, this commit should fix the issue https://github.com/ivan-hc/Bottles-appimage/commit/1e2852597c8abc6b7194ee2f51548fc73cacecbc

Can you confirm?

**Comment by ivan-hc** [comment]
about wine-gecko and wine-mono, I've not included them since I don't include wine itself, but just its dependences, fos sizes reasons (the AppImage is too big), and Bottles already installs its own wine version (soda) and related mono/gecko runtimes

**Comment by newyorkthink** [comment]
bug is fixed, i answer for the https://github.com/ivan-hc/Boxes-appimage/issues/3
