### ISSUE TITLE
GUI is WHITE for me :(

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ivan-hc/Bottles-appimage#12]
But in `.config/gtk-3.0/settings.ini ` I have 

`gtk-application-prefer-dark-theme=true`

**Comment by ivan-hc** [comment]
Bottles is based on GTK4

To solve the issue, you need to add the line
```
GTK_THEME=Adwaita-dark
```
to the /etc/environment file.

This is how I have solved with all my GTK4-based apps on XFCE.

PS: its not my fault if libadwaita/gtk4 sucks

**Comment by vitaly-zdanevich** [comment]
Added, but still white :(

Also tried

`GTK_THEME=Adwaita-dark FUSERMOUNT_PROG=$(which fusermount) ./Bottles-51.13-x86_64.AppImage `

**Comment by ivan-hc** [comment]
have you rebooted?

**Comment by vitaly-zdanevich** [comment]
Yes.

**Comment by vitaly-zdanevich** [comment]
Solved by preferences of Bottles
![image](https://github.com/user-attachments/assets/6bb87468-90c1-4127-9f1d-4c4abe212a7e)
