### ISSUE TITLE
Help me implement hardware accelleration for 64-bit games

### ISSUE THREAD

**Issue by ivan-hc** [ivan-hc/Bottles-appimage#2]
Ciao @mirkobrombin and @francescomasala , buon anno nuovo

I know that you are the maintainers of the AUR package on which this Appimage is built on. Also I've already talked with Mirko in the past trying to help him with the Apprun of the old and no more supported AppImage.

I know that is an assle when people that use third-party packages go asking to the upstream for support, when the fault is of the packager instead. Well, I package a lot of AppImages and I still receive bug report (è una bella rottura di coglioni, ma me la sono cercata).

Sorry if I bother you, I use my own method to package AppImages, I've called it [ArchImage](https://github.com/ivan-hc/ArchImage) and it is based on [JuNest](https://github.com/fsquillace/junest) (se siete fan di @morrolinux andatevi a recuperare la [video-recensione](https://www.youtube.com/watch?v=-PGz2qFYoZc)).

In brief, this is a portable container of Arch Linux that uses PROOT to be bundled into an AppImage.

You can consult the [script](https://github.com/ivan-hc/Bottles-appimage/blob/main/bottles-junest.sh) I use to build it and the [Workflows](https://github.com/ivan-hc/Bottles-appimage/actions/workflows/CI.yml) in Github Actions to understand how it works.

My only machine runs Debian Testing with an old NVIDIA GeForce GT 710:

- I've tested two 32-bits games (Diablo II LOD and FIFA 2004) and both work like a charm;
- I've tested the more recent release of SuperTuxKart for Windows, all works until the "loading screen" of the game (menus and animations are working, but I cant perform a gameplay).

This is the last step I have to do to made it work also on systems with the Linux kernel version 2.6 (as its said on the repo of JuNest).

I'm sure that the solutions are two:

- Should I use an environment variable in AppRun that I don't know about?
- Or should I use the option "--bind" of the internal PROOT or something to mount some directories on the host?

Mi affido a voi, cercate di non abbandonarmi. Grazie

**Comment by mirkobrombin** [comment]
Can you contact me on Discord (mirkob1) to have an easier conversation?

**Comment by ivan-hc** [comment]
@mirkobrombin just subscribed, I sent you a request

**Comment by ivan-hc** [comment]
Thank you Mirko!

https://github.com/ivan-hc/Bottles-appimage/blob/main/bottles.sh
