### ISSUE TITLE
Does not start the installation of the program, as well as from the shortcut

### ISSUE THREAD

**Issue by Alter-RK** [ivan-hc/Bottles-appimage#6]
Good afternoon. 

Debian GNU/Linux trixie/sid

I downloaded app images, launched it and created a prefix. You can run the program if you create a shortcut from the interface. But if you need to run the installation of the program, it writes an error in the console:

`wine: Failed to open the working directory "unix\\home\\alter\\.local\\share\\bottles\\bottles\\3D applications\\" located in the Windows directory.`

In addition, it creates a shortcut to the system, but does not launch it. I think because the start line looks like: 

`Exec=bottles-cli run -p blender -b '3D-Apps' -- %u`

But bottles-cli is not registered in the system. 

I hope I explained it clearly, English is not my native language

**Comment by ivan-hc** [comment]
This is normal, the AppImage is just one file. All you can do is to symlink it as "bottles", however I've not included a "bottles-cli" as an option. In such case it would be enough to create also a symlink named "bottles-cli". I'm doing some tests on my PC (I've the same distro of yours).

**Comment by ivan-hc** [comment]
Just updated the package https://github.com/ivan-hc/Bottles-appimage/commit/effe056c99024b0e6ae14ec63e8362aff9b44c9e

and also the usage with "AM" and AppMan https://github.com/ivan-hc/AM/commit/8d70f34192df3842778badc390092d1fe53bc2bb

Let me know if it works for you. All you need is a symlink in $PATH named "bottles-cli", and "AM"/AppMan already create it for you.

**Comment by ivan-hc** [comment]
About runnig .exe files from external paths, I get this error too:
```
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: could not open working directory L"unix\\media\\ivan\\userdata\\Giochi\\SuperTuxKart\\", starting in the Windows directory.
```
I don't know if I have to add other environment variables for this or something

**Comment by Alter-RK** [comment]
Created a shortcut and updated Bottles-51.10-1-x86_64.AppImage:

alter@lp-Alter:~$ sudo ln -s /opt/appimages/bottles.AppImage /usr/local/bin/bottles-cli

After that, program shortcuts began to be created. But they don't start

alter@lp-Alter:~$ bottles-cli run -p 'Blender_2.79b (wine)' -b '3D-Apps' -- %u
Unknown option -cli

**Comment by ivan-hc** [comment]
Just started another workflow https://github.com/ivan-hc/Bottles-appimage/actions/runs/8256461338

However, I'm investigating on the reason because wine cannot access external .exe files and I've found it. The Z: unit only shows the AppImage content.

In the meantime you can wait the end of the above workflow run before you download the AppImage again.

**Comment by ivan-hc** [comment]
With the next change (available at the end of this workflow run https://github.com/ivan-hc/Bottles-appimage/actions/runs/8257986346 ) it is possible to run executables from /home, /mnt and /media but only if you find them in Z:, under "obsolete wine tools/explore files"

**Comment by ivan-hc** [comment]
Nothing to do, the best thing to do would be to remove libunionpreload from the root of the AppImage, but without it the AppImage does not work. I can get a message about a missing "/usr/share/bottles/bottles.gresource" file that, instead, is already there.

I've also tried to rebuild the [Archimage](https://github.com/ivan-hc/Bottles-appimage/blob/main/legacy/bottles-junest.sh) by exporting local libraries, there I get some Xorg errors and sometime the app crashes.

**Comment by Alter-RK** [comment]
Thanks! The installation has started working)
