### ISSUE TITLE
Poorly written instructions.

### ISSUE THREAD

**Issue by raymerjacque** [ivan-hc/Bottles-appimage#7]
WOW, i am shocked at the poorly written instructions... no guide. just brief notes here and there... no wonder this project hasnt gained much support. take some pride in your work man.

**Comment by ivan-hc** [comment]
Unfortunately, the upstream developers only work for the official build in Flatpak format. If I consult their "issues" I can only see what they have changed in the lines of code... but there is not much information on how to build it on a normal distribution.

I would have preferred to compile it from GIT instead of merging two of my projects to create this "Debian+Arch Linux" hybrid.

**Comment by ivan-hc** [comment]
I hope this [README](https://github.com/ivan-hc/Bottles-appimage/blob/main/README.md) is OK, for you and for that asshole that said shit on Reddit about my amateur project. Bye.

**Comment by laike9m** [comment]
@raymerjacque Bottles-appimage has 8 stars, while your most [popular project](https://github.com/raymerjacque/leonardo.ai) got 2. Guess someone needs to work harder to gain some support 😉

**Comment by raymerjacque** [comment]
> @raymerjacque Bottles-appimage has 8 stars, while your most [popular project](https://github.com/raymerjacque/leonardo.ai) got 2. Guess someone needs to work harder to gain some support 😉

oh, another beta male... here is a tissue ....

**Comment by laike9m** [comment]
@raymerjacque Are you even a real human? You speak like a bot someone created, and I feel really sorry for that person.

**Comment by laike9m** [comment]
I'm assuming your creator hasn't been working very hard, otherwise you won't be so stupid.

**Comment by raymerjacque** [comment]
> @raymerjacque Are you even a real human? You speak like a bot someone created, and I feel really sorry for that person.

does the ccp know you are using a vpn to browse the internet ?

**Comment by laike9m** [comment]
Oh the bot knows a lot, good job, keep going
