### ISSUE TITLE
Does not launch with error: execv error: No such file or directory

### ISSUE THREAD

**Issue by akram1** [ivan-hc/Bottles-appimage#9]
I am using Manjaro (Arch Linux) latest. AppImage is installed and using couple of appimages but Wine is not  installed, when launched in terminal 

./Bottles-51.11-2-Type3-x86_64_57d2ed7adf4d802143338c809acee9ff.AppImage 

It gives me this error
execv error: No such file or directory

**Comment by ivan-hc** [comment]
why that name is so long?
```
Bottles-51.11-2-Type3-x86_64_57d2ed7adf4d802143338c809acee9ff.AppImage
```
have you tried to build it by yourself using the script?

If so, note that the python version in Arch Linux is changed, its now 3.12, while the ne used in the AUR package is still the 3.11, this is why I can't update the AppImage until they switch.

See https://github.com/ivan-hc/Bottles-appimage/issues/8

**Comment by akram1** [comment]
No I did not build it. I just downloaded your appimage. Then double click on it to luanch it with AppImage Launcher. Then the Launcher takes it from download to the AppImage folder and postfix the file name with some weird number like 57d2ed7adf4d802143338c809acee9ff.  My system has Python 3.11.8 but has no Wine. The followings are installed Python packages
Package             Version
------------------- -----------
annotated-types     0.6.0
apparmor            3.1.7
application-utility 1.3.2
attrs               23.2.0
autocommand         2.2.2
btrfsutil           6.7.1
catfish             4.18.0
certifi             2024.2.2
cffi                1.16.0
charset-normalizer  3.3.2
cryptography        41.0.7
dbus-python         1.3.2
docopt              0.6.2
idna                3.6
inflect             7.0.0
jaraco.context      4.3.0
jaraco.functools    4.0.0
jaraco.text         3.12.0
keyutils            0.6
LibAppArmor         3.1.7
lit                 16.0.6.dev0
manjaro-sdk         0.1.1
more-itertools      10.1.0
nftables            0.1
npyscreen           4.10.5
packaging           23.2
pacman_mirrors      4.24.0
pexpect             4.9.0
pillow              10.2.0
pip                 24.0
ply                 3.11
ptyprocess          0.7.0
pwquality           1.4.5
pycairo             1.26.0
pycparser           2.21
pydantic            2.6.3
pydantic_core       2.16.3
pyelftools          0.30
PyGObject           3.46.0
PyQt6               6.6.1
PyQt6-sip           13.6.0
PyQt6-WebEngine     6.6.0
PySide6             6.6.2
PyYAML              6.0.1
requests            2.31.0
shiboken6           6.6.2
shiboken6-generator 6.6.2
smbus               1.1
systemd-python      235
typing_extensions   4.10.0
udiskie             2.5.2
urllib3             1.26.18
wheel               0.42.0
yt-dlp              2023.

**Comment by ivan-hc** [comment]
have you tried to run it normally (without appimagelauncher) or using [AM](https://github.com/ivan-hc/AM)/[AppMan](https://github.com/ivan-hc/AppMan)?

**Comment by ivan-hc** [comment]
Appimagelauncher is a quite old AppImage manager and the last stable build was released in 2020, the latest development build in 2022.

I suggest to change AppImage manager.

Again I suggest to use my package manager "AM", at https://github.com/ivan-hc/AM , else run it manually
```
chmod a+x ./*AppImage
./*.AppImage
```
or use the GearLever (is a Flatpak).

I close this issue for inactivity.
